<%
Sub GetGlobalPrivileges(iPrivilegios)
Select Case iPrivilegios
	case 0
		response.write "<table width=""100%""  border=""1"" align=""center"" cellpadding=""2"" cellspacing=""1"" bordercolor=""#E2E2E2"" style=""margin: 0px 0px 0px 0px;"">"
		response.write " <tr>"
		response.write "<td width=""50%"" class=""h_text""><div align=""right"">Alta</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalA"" value=""chkGlobalA"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalA"" value=""1"">"
		response.write "</div>"
		response.write "<div align=""center""></div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Baja</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalB"" value=""chkGlobalB"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalB"" value=""1"">"
		response.write "</div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Modificaci&oacute;n</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalM"" value=""chkGlobalM"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalM"" value=""1"">"
		response.write "</div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Lectura</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalL"" value=""chkGlobalL"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalL"" value=""1"">"
		response.write "</div></td>"
		response.write " </tr>"
		response.write "</table>"
	case 1
		response.write "<table width=""100%""  border=""1"" align=""center"" cellpadding=""2"" cellspacing=""1"" bordercolor=""#E2E2E2"" style=""margin: 0px 0px 0px 0px;"">"
		response.write " <tr>"
		response.write "<td width=""50%"" class=""h_text""><div align=""right"">Alta</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalA"" value=""chkGlobalA"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalA"" value=""1"">"
		response.write "</div>"
		response.write "<div align=""center""></div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Baja</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalB"" value=""chkGlobalB"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalB"" value=""1"">"
		response.write "</div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Modificaci&oacute;n</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalM"" value=""chkGlobalM"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalM"" value=""1"">"
		response.write "</div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Lectura</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalL"" value=""chkGlobalL"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalL"" value=""1"" checked>"
		response.write "</div></td>"
		response.write " </tr>"
		response.write "</table>"
	case 2
		response.write "<table width=""100%""  border=""1"" align=""center"" cellpadding=""2"" cellspacing=""1"" bordercolor=""#E2E2E2"" style=""margin: 0px 0px 0px 0px;"">"
		response.write " <tr>"
		response.write "<td width=""50%"" class=""h_text""><div align=""right"">Alta</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalA"" value=""chkGlobalA"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalA"" value=""1"">"
		response.write "</div>"
		response.write "<div align=""center""></div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Baja</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalB"" value=""chkGlobalB"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalB"" value=""1"">"
		response.write "</div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Modificaci&oacute;n</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalM"" value=""chkGlobalM"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalM"" value=""1"" checked>"
		response.write "</div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Lectura</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalL"" value=""chkGlobalL"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalL"" value=""1"">"
		response.write "</div></td>"
		response.write " </tr>"
		response.write "</table>"
	case 3
		response.write "<table width=""100%""  border=""1"" align=""center"" cellpadding=""2"" cellspacing=""1"" bordercolor=""#E2E2E2"" style=""margin: 0px 0px 0px 0px;"">"
		response.write " <tr>"
		response.write "<td width=""50%"" class=""h_text""><div align=""right"">Alta</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalA"" value=""chkGlobalA"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalA"" value=""1"">"
		response.write "</div>"
		response.write "<div align=""center""></div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Baja</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalB"" value=""chkGlobalB"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalB"" value=""1"">"
		response.write "</div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Modificaci&oacute;n</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalM"" value=""chkGlobalM"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalM"" value=""1"" checked>"
		response.write "</div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Lectura</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalL"" value=""chkGlobalL"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalL"" value=""1"" checked>"
		response.write "</div></td>"
		response.write " </tr>"
		response.write "</table>"
	case 4
		response.write "<table width=""100%""  border=""1"" align=""center"" cellpadding=""2"" cellspacing=""1"" bordercolor=""#E2E2E2"" style=""margin: 0px 0px 0px 0px;"">"
		response.write " <tr>"
		response.write "<td width=""50%"" class=""h_text""><div align=""right"">Alta</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalA"" value=""chkGlobalA"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalA"" value=""1"">"
		response.write "</div>"
		response.write "<div align=""center""></div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Baja</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalB"" value=""chkGlobalB"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalB"" value=""1"" checked>"
		response.write "</div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Modificaci&oacute;n</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalM"" value=""chkGlobalM"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalM"" value=""1"">"
		response.write "</div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Lectura</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalL"" value=""chkGlobalL"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalL"" value=""1"">"
		response.write "</div></td>"
		response.write " </tr>"
		response.write "</table>"
	case 5
		response.write "<table width=""100%""  border=""1"" align=""center"" cellpadding=""2"" cellspacing=""1"" bordercolor=""#E2E2E2"" style=""margin: 0px 0px 0px 0px;"">"
		response.write " <tr>"
		response.write "<td width=""50%"" class=""h_text""><div align=""right"">Alta</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalA"" value=""chkGlobalA"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalA"" value=""1"">"
		response.write "</div>"
		response.write "<div align=""center""></div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Baja</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalB"" value=""chkGlobalB"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalB"" value=""1"" checked>"
		response.write "</div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Modificaci&oacute;n</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalM"" value=""chkGlobalM"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalM"" value=""1"">"
		response.write "</div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Lectura</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalL"" value=""chkGlobalL"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalL"" value=""1"" checked>"
		response.write "</div></td>"
		response.write " </tr>"
		response.write "</table>"
	case 6
		response.write "<table width=""100%""  border=""1"" align=""center"" cellpadding=""2"" cellspacing=""1"" bordercolor=""#E2E2E2"" style=""margin: 0px 0px 0px 0px;"">"
		response.write " <tr>"
		response.write "<td width=""50%"" class=""h_text""><div align=""right"">Alta</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalA"" value=""chkGlobalA"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalA"" value=""1"">"
		response.write "</div>"
		response.write "<div align=""center""></div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Baja</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalB"" value=""chkGlobalB"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalB"" value=""1"" checked>"
		response.write "</div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Modificaci&oacute;n</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalM"" value=""chkGlobalM"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalM"" value=""1"" checked>"
		response.write "</div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Lectura</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalL"" value=""chkGlobalL"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalL"" value=""1"">"
		response.write "</div></td>"
		response.write " </tr>"
		response.write "</table>"
	case 7
		response.write "<table width=""100%""  border=""1"" align=""center"" cellpadding=""2"" cellspacing=""1"" bordercolor=""#E2E2E2"" style=""margin: 0px 0px 0px 0px;"">"
		response.write " <tr>"
		response.write "<td width=""50%"" class=""h_text""><div align=""right"">Alta</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalA"" value=""chkGlobalA"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalA"" value=""1"">"
		response.write "</div>"
		response.write "<div align=""center""></div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Baja</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalB"" value=""chkGlobalB"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalB"" value=""1"" checked>"
		response.write "</div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Modificaci&oacute;n</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalM"" value=""chkGlobalM"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalM"" value=""1"" checked>"
		response.write "</div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Lectura</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalL"" value=""chkGlobalL"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalL"" value=""1"" checked>"
		response.write "</div></td>"
		response.write " </tr>"
		response.write "</table>"
	case 8
		response.write "<table width=""100%""  border=""1"" align=""center"" cellpadding=""2"" cellspacing=""1"" bordercolor=""#E2E2E2"" style=""margin: 0px 0px 0px 0px;"">"
		response.write " <tr>"
		response.write "<td width=""50%"" class=""h_text""><div align=""right"">Alta</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalA"" value=""chkGlobalA"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalA"" value=""1"" checked>"
		response.write "</div>"
		response.write "<div align=""center""></div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Baja</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalB"" value=""chkGlobalB"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalB"" value=""1"">"
		response.write "</div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Modificaci&oacute;n</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalM"" value=""chkGlobalM"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalM"" value=""1"">"
		response.write "</div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Lectura</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalL"" value=""chkGlobalL"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalL"" value=""1"">"
		response.write "</div></td>"
		response.write " </tr>"
		response.write "</table>"
	case 9
		response.write "<table width=""100%""  border=""1"" align=""center"" cellpadding=""2"" cellspacing=""1"" bordercolor=""#E2E2E2"" style=""margin: 0px 0px 0px 0px;"">"
		response.write " <tr>"
		response.write "<td width=""50%"" class=""h_text""><div align=""right"">Alta</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalA"" value=""chkGlobalA"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalA"" value=""1"" checked>"
		response.write "</div>"
		response.write "<div align=""center""></div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Baja</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalB"" value=""chkGlobalB"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalB"" value=""1"">"
		response.write "</div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Modificaci&oacute;n</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalM"" value=""chkGlobalM"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalM"" value=""1"">"
		response.write "</div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Lectura</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalL"" value=""chkGlobalL"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalL"" value=""1"" checked>"
		response.write "</div></td>"
		response.write " </tr>"
		response.write "</table>"
	case 10
		response.write "<table width=""100%""  border=""1"" align=""center"" cellpadding=""2"" cellspacing=""1"" bordercolor=""#E2E2E2"" style=""margin: 0px 0px 0px 0px;"">"
		response.write " <tr>"
		response.write "<td width=""50%"" class=""h_text""><div align=""right"">Alta</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalA"" value=""chkGlobalA"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalA"" value=""1"" checked>"
		response.write "</div>"
		response.write "<div align=""center""></div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Baja</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalB"" value=""chkGlobalB"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalB"" value=""1"">"
		response.write "</div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Modificaci&oacute;n</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalM"" value=""chkGlobalM"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalM"" value=""1"" checked>"
		response.write "</div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Lectura</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalL"" value=""chkGlobalL"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalL"" value=""1"">"
		response.write "</div></td>"
		response.write " </tr>"
		response.write "</table>"
	case 11
		response.write "<table width=""100%""  border=""1"" align=""center"" cellpadding=""2"" cellspacing=""1"" bordercolor=""#E2E2E2"" style=""margin: 0px 0px 0px 0px;"">"
		response.write " <tr>"
		response.write "<td width=""50%"" class=""h_text""><div align=""right"">Alta</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalA"" value=""chkGlobalA"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalA"" value=""1"" checked>"
		response.write "</div>"
		response.write "<div align=""center""></div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Baja</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalB"" value=""chkGlobalB"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalB"" value=""1"">"
		response.write "</div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Modificaci&oacute;n</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalM"" value=""chkGlobalM"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalM"" value=""1"" checked>"
		response.write "</div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Lectura</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalL"" value=""chkGlobalL"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalL"" value=""1"" checked>"
		response.write "</div></td>"
		response.write " </tr>"
		response.write "</table>"
	case 12
		response.write "<table width=""100%""  border=""1"" align=""center"" cellpadding=""2"" cellspacing=""1"" bordercolor=""#E2E2E2"" style=""margin: 0px 0px 0px 0px;"">"
		response.write " <tr>"
		response.write "<td width=""50%"" class=""h_text""><div align=""right"">Alta</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalA"" value=""chkGlobalA"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalA"" value=""1"" checked>"
		response.write "</div>"
		response.write "<div align=""center""></div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Baja</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalB"" value=""chkGlobalB"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalB"" value=""1"" checked>"
		response.write "</div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Modificaci&oacute;n</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalM"" value=""chkGlobalM"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalM"" value=""1"">"
		response.write "</div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Lectura</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalL"" value=""chkGlobalL"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalL"" value=""1"">"
		response.write "</div></td>"
		response.write " </tr>"
		response.write "</table>"
	case 13
		response.write "<table width=""100%""  border=""1"" align=""center"" cellpadding=""2"" cellspacing=""1"" bordercolor=""#E2E2E2"" style=""margin: 0px 0px 0px 0px;"">"
		response.write " <tr>"
		response.write "<td width=""50%"" class=""h_text""><div align=""right"">Alta</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalA"" value=""chkGlobalA"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalA"" value=""1"" checked>"
		response.write "</div>"
		response.write "<div align=""center""></div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Baja</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalB"" value=""chkGlobalB"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalB"" value=""1"" checked>"
		response.write "</div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Modificaci&oacute;n</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalM"" value=""chkGlobalM"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalM"" value=""1"">"
		response.write "</div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Lectura</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalL"" value=""chkGlobalL"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalL"" value=""1"" checked>"
		response.write "</div></td>"
		response.write " </tr>"
		response.write "</table>"
	case 14
		response.write "<table width=""100%""  border=""1"" align=""center"" cellpadding=""2"" cellspacing=""1"" bordercolor=""#E2E2E2"" style=""margin: 0px 0px 0px 0px;"">"
		response.write " <tr>"
		response.write "<td width=""50%"" class=""h_text""><div align=""right"">Alta</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalA"" value=""chkGlobalA"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalA"" value=""1"" checked>"
		response.write "</div>"
		response.write "<div align=""center""></div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Baja</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalB"" value=""chkGlobalB"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalB"" value=""1"" checked>"
		response.write "</div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Modificaci&oacute;n</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalM"" value=""chkGlobalM"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalM"" value=""1"" checked>"
		response.write "</div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Lectura</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalL"" value=""chkGlobalL"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalL"" value=""1"">"
		response.write "</div></td>"
		response.write " </tr>"
		response.write "</table>"
	case 15
		response.write "<table width=""100%""  border=""1"" align=""center"" cellpadding=""2"" cellspacing=""1"" bordercolor=""#E2E2E2"" style=""margin: 0px 0px 0px 0px;"">"
		response.write " <tr>"
		response.write "<td width=""50%"" class=""h_text""><div align=""right"">Alta</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalA"" value=""chkGlobalA"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalA"" value=""1"" checked>"
		response.write "</div>"
		response.write "<div align=""center""></div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Baja</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalB"" value=""chkGlobalB"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalB"" value=""1"" checked>"
		response.write "</div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Modificaci&oacute;n</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalM"" value=""chkGlobalM"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalM"" value=""1"" checked>"
		response.write "</div></td>"
		response.write " </tr>"
		response.write " <tr>"
		response.write "<td class=""h_text""><div align=""right"">Lectura</div></td>"
		response.write "<td class=""h_text""><div align=""center"">"
		response.write "<input type=""hidden"" name=""meta_chkGlobalL"" value=""chkGlobalL"">"
		response.write "  <input type=""checkbox"" name=""chkGlobalL"" value=""1"" checked>"
		response.write "</div></td>"
		response.write " </tr>"
		response.write "</table>"
End Select
End Sub	

Sub GetTablesPrivileges(sXML)
Dim oRs
Dim oDOM

	Set oDOM = Server.CreateObject("MSXML2.DOMDocument")
	Set oRs = Server.CreateObject("ADODB.Recordset")
	
	If oDOM.loadXML(sXML) Then
		Set oRs = RecordsetFromXMLDocument(oDOM)
		
		While Not oRs.EOF
			if Instr(1,  oRs("Tabla"), "_", 1) or oRs("Tabla") = "tablas" or oRs("Tabla") = "campos" or oRs("Tabla") = "restricciones" or oRs("Tabla") = "operaciones" or oRs("Tabla") = "roles" then 
				oRs.MoveNext
			else
				DrawTablesPrivileges oRs("Tabla"), IIf(isNull(oRs("Permiso")), "0", oRs("Permiso"))
				oRs.MoveNext
			End if
		Wend
	End if

End Sub

Sub DrawTablesPrivileges(sTabla, iPrivilegios)
	Select Case iPrivilegios
		case 0, NULL
			response.write "						<tr>"
			response.write "                           <td class=""h_text""><div align=""center"">" & sTabla & "</div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "A"" value=""chk" & sTabla & "A"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "A"" value=""1"">"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "B"" value=""chk" & sTabla & "B"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "B"" value=""1"">"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "M"" value=""chk" & sTabla & "M"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "M"" value=""1"">"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "L"" value=""chk" & sTabla & "L"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "L"" value=""1"">"
			response.write "                           </span></div></td>"
			response.write "                         </tr>"
		case 1
			response.write "						<tr>"
			response.write "                           <td class=""h_text""><div align=""center"">" & sTabla & "</div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "A"" value=""chk" & sTabla & "A"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "A"" value=""1"">"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "B"" value=""chk" & sTabla & "B"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "B"" value=""1"">"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "M"" value=""chk" & sTabla & "M"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "M"" value=""1"">"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "L"" value=""chk" & sTabla & "L"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "L"" value=""1"" checked>"
			response.write "                           </span></div></td>"
			response.write "                         </tr>"
		case 2
			response.write "						<tr>"
			response.write "                           <td class=""h_text""><div align=""center"">" & sTabla & "</div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "A"" value=""chk" & sTabla & "A"">"
response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "A"" value=""1"">"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "B"" value=""chk" & sTabla & "B"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "B"" value=""1"">"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "M"" value=""chk" & sTabla & "M"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "M"" value=""1"" checked>"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "L"" value=""chk" & sTabla & "L"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "L"" value=""1"">"
			response.write "                           </span></div></td>"
			response.write "                         </tr>"
		case 3
			response.write "						<tr>"
			response.write "                           <td class=""h_text""><div align=""center"">" & sTabla & "</div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "A"" value=""chk" & sTabla & "A"">"
response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "A"" value=""1"">"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "B"" value=""chk" & sTabla & "B"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "B"" value=""1"">"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "M"" value=""chk" & sTabla & "M"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "M"" value=""1"" checked>"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "L"" value=""chk" & sTabla & "L"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "L"" value=""1"" checked>"
			response.write "                           </span></div></td>"
			response.write "                         </tr>"
		case 4
			response.write "						<tr>"
			response.write "                           <td class=""h_text""><div align=""center"">" & sTabla & "</div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "A"" value=""chk" & sTabla & "A"">"
response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "A"" value=""1"">"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "B"" value=""chk" & sTabla & "B"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "B"" value=""1"" checked>"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "M"" value=""chk" & sTabla & "M"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "M"" value=""1"">"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "L"" value=""chk" & sTabla & "L"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "L"" value=""1"">"
			response.write "                           </span></div></td>"
			response.write "                         </tr>"
		case 5
			response.write "						<tr>"
			response.write "                           <td class=""h_text""><div align=""center"">" & sTabla & "</div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "A"" value=""chk" & sTabla & "A"">"
response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "A"" value=""1"">"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "B"" value=""chk" & sTabla & "B"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "B"" value=""1"" checked>"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "M"" value=""chk" & sTabla & "M"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "M"" value=""1"">"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "L"" value=""chk" & sTabla & "L"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "L"" value=""1"" checked>"
			response.write "                           </span></div></td>"
			response.write "                         </tr>"
		case 6
			response.write "						<tr>"
			response.write "                           <td class=""h_text""><div align=""center"">" & sTabla & "</div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "A"" value=""chk" & sTabla & "A"">"
response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "A"" value=""1"">"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "B"" value=""chk" & sTabla & "B"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "B"" value=""1"" checked>"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "M"" value=""chk" & sTabla & "M"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "M"" value=""1"" checked>"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "L"" value=""chk" & sTabla & "L"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "L"" value=""1"">"
			response.write "                           </span></div></td>"
			response.write "                         </tr>"
		case 7
			response.write "						<tr>"
			response.write "                           <td class=""h_text""><div align=""center"">" & sTabla & "</div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "A"" value=""chk" & sTabla & "A"">"
response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "A"" value=""1"">"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "B"" value=""chk" & sTabla & "B"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "B"" value=""1"" checked>"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "M"" value=""chk" & sTabla & "M"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "M"" value=""1"" checked>"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "L"" value=""chk" & sTabla & "L"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "L"" value=""1"" checked>"
			response.write "                           </span></div></td>"
			response.write "                         </tr>"
		case 8
			response.write "						<tr>"
			response.write "                           <td class=""h_text""><div align=""center"">" & sTabla & "</div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "A"" value=""chk" & sTabla & "A"">"
response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "A"" value=""1"" checked>"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "B"" value=""chk" & sTabla & "B"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "B"" value=""1"">"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "M"" value=""chk" & sTabla & "M"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "M"" value=""1"">"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "L"" value=""chk" & sTabla & "L"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "L"" value=""1"">"
			response.write "                           </span></div></td>"
			response.write "                         </tr>"
		case 9
			response.write "						<tr>"
			response.write "                           <td class=""h_text""><div align=""center"">" & sTabla & "</div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "A"" value=""chk" & sTabla & "A"">"
response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "A"" value=""1"" checked>"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "B"" value=""chk" & sTabla & "B"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "B"" value=""1"">"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "M"" value=""chk" & sTabla & "M"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "M"" value=""1"">"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "L"" value=""chk" & sTabla & "L"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "L"" value=""1"" checked>"
			response.write "                           </span></div></td>"
			response.write "                         </tr>"
		case 10
			response.write "						<tr>"
			response.write "                           <td class=""h_text""><div align=""center"">" & sTabla & "</div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "A"" value=""chk" & sTabla & "A"">"
response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "A"" value=""1"" checked>"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "B"" value=""chk" & sTabla & "B"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "B"" value=""1"">"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "M"" value=""chk" & sTabla & "M"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "M"" value=""1"" checked>"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "L"" value=""chk" & sTabla & "L"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "L"" value=""1"">"
			response.write "                           </span></div></td>"
			response.write "                         </tr>"
		case 11
			response.write "						<tr>"
			response.write "                           <td class=""h_text""><div align=""center"">" & sTabla & "</div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "A"" value=""chk" & sTabla & "A"">"
response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "A"" value=""1"" checked>"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "B"" value=""chk" & sTabla & "B"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "B"" value=""1"">"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "M"" value=""chk" & sTabla & "M"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "M"" value=""1"" checked>"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "L"" value=""chk" & sTabla & "L"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "L"" value=""1"" checked>"
			response.write "                           </span></div></td>"
			response.write "                         </tr>"
		case 12
			response.write "						<tr>"
			response.write "                           <td class=""h_text""><div align=""center"">" & sTabla & "</div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "A"" value=""chk" & sTabla & "A"">"
response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "A"" value=""1"" checked>"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "B"" value=""chk" & sTabla & "B"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "B"" value=""1"" checked>"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "M"" value=""chk" & sTabla & "M"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "M"" value=""1"">"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "L"" value=""chk" & sTabla & "L"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "L"" value=""1"">"
			response.write "                           </span></div></td>"
			response.write "                         </tr>"
		case 13
			response.write "						<tr>"
			response.write "                           <td class=""h_text""><div align=""center"">" & sTabla & "</div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "A"" value=""chk" & sTabla & "A"">"
response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "A"" value=""1"" checked>"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "B"" value=""chk" & sTabla & "B"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "B"" value=""1"">"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "M"" value=""chk" & sTabla & "M"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "M"" value=""1"" checked>"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "L"" value=""chk" & sTabla & "L"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "L"" value=""1"" checked>"
			response.write "                           </span></div></td>"
			response.write "                         </tr>"
		case 14
			response.write "						<tr>"
			response.write "                           <td class=""h_text""><div align=""center"">" & sTabla & "</div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "A"" value=""chk" & sTabla & "A"">"
response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "A"" value=""1"" checked>"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "B"" value=""chk" & sTabla & "B"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "B"" value=""1"" checked>"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "M"" value=""chk" & sTabla & "M"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "M"" value=""1"" checked>"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "L"" value=""chk" & sTabla & "L"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "L"" value=""1"">"
			response.write "                           </span></div></td>"
			response.write "                         </tr>"
		case 15
			response.write "						<tr>"
			response.write "                           <td class=""h_text""><div align=""center"">" & sTabla & "</div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "A"" value=""chk" & sTabla & "A"">"
response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "A"" value=""1"" checked>"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "B"" value=""chk" & sTabla & "B"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "B"" value=""1"" checked>"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "M"" value=""chk" & sTabla & "M"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "M"" value=""1"" checked>"
			response.write "                           </span></div></td>"
			response.write "                           <td><div align=""center""><span class=""h_text"">"
			response.write "							 <input type=""hidden"" name=""meta_chk" & sTabla & "L"" value=""chk" & sTabla & "L"">"
			response.write "                             <input type=""checkbox"" name=""chk" & sTabla & "L"" value=""1"" checked>"
			response.write "                           </span></div></td>"
			response.write "                         </tr>"
	End Select
End Sub

Sub DrawRestrictions(sXML, iRolID)
Dim bDeleted
Dim oRs
Dim oDOM
Dim j

	Set oDOM = Server.CreateObject("MSXML2.DOMDocument")
	Set oRs = Server.CreateObject("ADODB.Recordset")
	
	If oDOM.loadXML(sXML) Then
		'oRs.CursorLocation = 3
		Set oRs = RecordsetFromXMLDocument(oDOM)
		
		'oRS.Sort = "ID ASC"

		While Not oRs.EOF
			
			bDeleted = IIf(Len(oRs("Fecha_Baja")) > 0, true, false)
			If bDeleted then
				response.write "<tr bgcolor=""#F2AAB1"">"
			Else
				response.write "<tr>"
			End If		
			response.write "	<td class=""h_text""><div align=""center"">" & oRs("tabla") & "</div></td>"
			response.write "	<td class=""h_text""><div align=""center"">" & oRs("campo") & "</td>"
			response.write "	<td><div align=""center""><span class=""h_text"">" & oRs("operacion") & "</span></div></td>"
			response.write "	<td><div align=""center""><span class=""h_text"">""" & oRs("valor") & """</span></div></td>"
			response.write "<td class=""l_text"" bgcolor=""#FFFFFF""><div align=""center""><a class=""l_text"" onClick=""myRef = window.open('restricciones_update.asp?ID=" & oRs("ID") & "&IDBack=" & iRolID & "','mywin','left=200,top=200,width=600,height=1,scrollbars=0,toolbar=0,resizable=0,menubar=0'); myRef.focus()"" href=""javascript:void(0);"">editar</a></div></td>"		
			response.write "<td class=""l_text"" bgcolor=""#FFFFFF""><div align=""center"">"

		If bDeleted then
			response.write "<a class=""l_text"" href=""restricciones_recover.asp?ID=" & oRs("ID") & "&IDback=" & iRolID & """ onclick=""return confirm('¿Está seguro que desea recuperar el registro?')"">recuperar</a>"
		Else
			response.write "<a class=""l_text"" href=""restricciones_delete.asp?ID=" & oRs("ID") & "&IDback=" & iRolID & """ onclick=""return confirm('¿Está seguro que desea eliminar el registro?')"">eliminar</a>"
		End If

		response.write "</div></td>"
		response.write "</tr>"

			oRs.MoveNext
		Wend

	End If

End Sub

Function Bin2Dec(Num)
Dim n, a, x
     n = Len(Num) - 1      
	 a = n 
	 Bin2Dec = 0
     Do While n > -1 
        x = Mid(Num, ((a + 1) - n), 1) 
        Bin2Dec = IIf((x = "1"), Bin2Dec + (2 ^ (n)), Bin2Dec) 
        n = n - 1 
     Loop 
End Function
%>